defaults:
  - _self_
  - data: spine_generic
  - network: deformable
  - transformation: bspline
  - loss: nmi
  - training: training
  - regularization: bending
  - wandb_cfg: defaults

metric_groups: ["disp_metrics", "image_metrics", "seg_metrics"]
hparam_metrics: ["loss", "mean_dice", "folding_ratio"]

analyse: True
analyse_only: False

wandb_disable: "False"
verbose: 1
gpu: 1
baselines: False
slurm: False

hydra:
    job:
        chdir: True

